services:
  - type: web
    name: strapi
    runtime: node
    plan: starter
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start
    healthCheckPath: /_health
    autoDeploy: false
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 1337
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_SSL
        value: false
      - key: DATABASE_HOST
        fromDatabase:
          name: strapi
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: strapi
          property: port
      - key: TRANSFER_TOKEN_SALT
        sync: false
      - key: API_TOKEN_SALT
        sync: false
      - key: NODE_ENV
        value: production
      - key: DATABASE_NAME
        fromDatabase:
          name: strapi
          property: database
      - key: DATABASE_USERNAME
        fromDatabase:
          name: strapi
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: strapi
          property: password
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: APP_KEYS
        sync: false
      - key: R2_ACCESS_KEY
        sync: false
      - key: R2_SECRET_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_ENDPOINT
        sync: false
      - key: R2_PUBLIC_ACCESS_URL
        sync: false

databases:
  - name: strapi
    plan: starter
