// Interface automatically generated by schemas-to-ts

export interface BulletPoint {
  bulletPointText: string;
}
export interface BulletPoint_Plain {
  bulletPointText: string;
}

export interface BulletPoint_NoRelations {
  bulletPointText: string;
}

