// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Link } from '../../../../components/link/interfaces/Link';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Link_Plain } from '../../../../components/link/interfaces/Link';
import { Link_NoRelations } from '../../../../components/link/interfaces/Link';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Footer {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    logo: { data: Media };
    logoTitle?: string;
    logoSubtitle?: string;
    address?: string;
    bodyText: string;
    accoladesOrSponsorImages?: { data: Media[] };
    links: Link[];
    bottomRightDecoration?: { data: Media };
    copyrightNotice: string;
    leftImage: { data: Media };
    locale: string;
    localizations?: { data: Footer[] };
  };
}
export interface Footer_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logo: Media_Plain;
  logoTitle?: string;
  logoSubtitle?: string;
  address?: string;
  bodyText: string;
  accoladesOrSponsorImages?: Media_Plain[];
  links: Link_Plain[];
  bottomRightDecoration?: Media_Plain;
  copyrightNotice: string;
  leftImage: Media_Plain;
  locale: string;
  localizations?: Footer_Plain[];
}

export interface Footer_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logo: number;
  logoTitle?: string;
  logoSubtitle?: string;
  address?: string;
  bodyText: string;
  accoladesOrSponsorImages?: number[];
  links: Link_NoRelations[];
  bottomRightDecoration?: number;
  copyrightNotice: string;
  leftImage: number;
  locale: string;
  localizations?: Footer[];
}

export interface Footer_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logo: AdminPanelRelationPropertyModification<Media_Plain>;
  logoTitle?: string;
  logoSubtitle?: string;
  address?: string;
  bodyText: string;
  accoladesOrSponsorImages?: AdminPanelRelationPropertyModification<Media_Plain>[];
  links: Link_Plain[];
  bottomRightDecoration?: AdminPanelRelationPropertyModification<Media_Plain>;
  copyrightNotice: string;
  leftImage: AdminPanelRelationPropertyModification<Media_Plain>;
  locale: string;
  localizations?: Footer[];
}
