// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface MetaData {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    homepageTitle: string;
    subsequentPageTitleTemplate: string;
    homepageDescription: string;
    openGraphDescription: string;
    openGraphImage: { data: Media };
    locale: string;
    localizations?: { data: MetaData[] };
  };
}
export interface MetaData_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  homepageTitle: string;
  subsequentPageTitleTemplate: string;
  homepageDescription: string;
  openGraphDescription: string;
  openGraphImage: Media_Plain;
  locale: string;
  localizations?: MetaData_Plain[];
}

export interface MetaData_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  homepageTitle: string;
  subsequentPageTitleTemplate: string;
  homepageDescription: string;
  openGraphDescription: string;
  openGraphImage: number;
  locale: string;
  localizations?: MetaData[];
}

export interface MetaData_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  homepageTitle: string;
  subsequentPageTitleTemplate: string;
  homepageDescription: string;
  openGraphDescription: string;
  openGraphImage: AdminPanelRelationPropertyModification<Media_Plain>;
  locale: string;
  localizations?: MetaData[];
}
