// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Link } from '../../../../components/link/interfaces/Link';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Link_Plain } from '../../../../components/link/interfaces/Link';
import { Link_NoRelations } from '../../../../components/link/interfaces/Link';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Navbar {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    logo: { data: Media };
    name: string;
    announcementText?: string;
    announcementLink?: Link;
    address: string;
    email?: string;
    phoneNumber?: string;
    facebookLink?: string;
    instagramLink?: string;
    tiktokLink?: string;
    youtubeLink?: string;
    googleLink?: string;
    twitterLink?: string;
    linkedInLink?: string;
    snapchatLink?: string;
    homeLinks: Link[];
    aboutUsLinks: Link[];
    takeActionLinks: Link[];
    ridingProgramLinks: Link[];
    eventsAndActivitiesLinks: Link[];
    horseBoardingLinks: Link[];
    slogan?: string;
    donateButton?: Link;
    contactUsButton?: Link;
    locale: string;
    localizations?: { data: Navbar[] };
  };
}
export interface Navbar_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logo: Media_Plain;
  name: string;
  announcementText?: string;
  announcementLink?: Link_Plain;
  address: string;
  email?: string;
  phoneNumber?: string;
  facebookLink?: string;
  instagramLink?: string;
  tiktokLink?: string;
  youtubeLink?: string;
  googleLink?: string;
  twitterLink?: string;
  linkedInLink?: string;
  snapchatLink?: string;
  homeLinks: Link_Plain[];
  aboutUsLinks: Link_Plain[];
  takeActionLinks: Link_Plain[];
  ridingProgramLinks: Link_Plain[];
  eventsAndActivitiesLinks: Link_Plain[];
  horseBoardingLinks: Link_Plain[];
  slogan?: string;
  donateButton?: Link_Plain;
  contactUsButton?: Link_Plain;
  locale: string;
  localizations?: Navbar_Plain[];
}

export interface Navbar_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logo: number;
  name: string;
  announcementText?: string;
  announcementLink?: Link_NoRelations;
  address: string;
  email?: string;
  phoneNumber?: string;
  facebookLink?: string;
  instagramLink?: string;
  tiktokLink?: string;
  youtubeLink?: string;
  googleLink?: string;
  twitterLink?: string;
  linkedInLink?: string;
  snapchatLink?: string;
  homeLinks: Link_NoRelations[];
  aboutUsLinks: Link_NoRelations[];
  takeActionLinks: Link_NoRelations[];
  ridingProgramLinks: Link_NoRelations[];
  eventsAndActivitiesLinks: Link_NoRelations[];
  horseBoardingLinks: Link_NoRelations[];
  slogan?: string;
  donateButton?: Link_NoRelations;
  contactUsButton?: Link_NoRelations;
  locale: string;
  localizations?: Navbar[];
}

export interface Navbar_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logo: AdminPanelRelationPropertyModification<Media_Plain>;
  name: string;
  announcementText?: string;
  announcementLink?: Link_Plain;
  address: string;
  email?: string;
  phoneNumber?: string;
  facebookLink?: string;
  instagramLink?: string;
  tiktokLink?: string;
  youtubeLink?: string;
  googleLink?: string;
  twitterLink?: string;
  linkedInLink?: string;
  snapchatLink?: string;
  homeLinks: Link_Plain[];
  aboutUsLinks: Link_Plain[];
  takeActionLinks: Link_Plain[];
  ridingProgramLinks: Link_Plain[];
  eventsAndActivitiesLinks: Link_Plain[];
  horseBoardingLinks: Link_Plain[];
  slogan?: string;
  donateButton?: Link_Plain;
  contactUsButton?: Link_Plain;
  locale: string;
  localizations?: Navbar[];
}
