// Interface automatically generated by schemas-to-ts

export interface Link {
  linkText: string;
  linkAddress: string;
}
export interface Link_Plain {
  linkText: string;
  linkAddress: string;
}

export interface Link_NoRelations {
  linkText: string;
  linkAddress: string;
}

