// Interface automatically generated by schemas-to-ts

export interface Banner {
  leftText?: string;
  facebookLink?: string;
  instagramLink?: string;
  tiktokLink?: string;
  youtubeLink?: string;
  googleLink?: string;
  twitterLink?: string;
  linkedInLink?: string;
  snapchatLink?: string;
}
export interface Banner_Plain {
  leftText?: string;
  facebookLink?: string;
  instagramLink?: string;
  tiktokLink?: string;
  youtubeLink?: string;
  googleLink?: string;
  twitterLink?: string;
  linkedInLink?: string;
  snapchatLink?: string;
}

export interface Banner_NoRelations {
  leftText?: string;
  facebookLink?: string;
  instagramLink?: string;
  tiktokLink?: string;
  youtubeLink?: string;
  googleLink?: string;
  twitterLink?: string;
  linkedInLink?: string;
  snapchatLink?: string;
}

