// Interface automatically generated by schemas-to-ts

export interface Banner {
  leftText?: string;
}
export interface Banner_Plain {
  leftText?: string;
}

export interface Banner_NoRelations {
  leftText?: string;
}

