// Interface automatically generated by schemas-to-ts

import { Link } from '../../link/interfaces/Link';
import { Link_Plain } from '../../link/interfaces/Link';
import { Link_NoRelations } from '../../link/interfaces/Link';

export interface Button {
  link: Link;
}
export interface Button_Plain {
  link: Link_Plain;
}

export interface Button_NoRelations {
  link: Link_NoRelations;
}

