// Interface automatically generated by schemas-to-ts

export interface Divider {
  centerText?: string;
}
export interface Divider_Plain {
  centerText?: string;
}

export interface Divider_NoRelations {
  centerText?: string;
}

