// Interface automatically generated by schemas-to-ts

export interface Padding {
  pixels: number;
}
export interface Padding_Plain {
  pixels: number;
}

export interface Padding_NoRelations {
  pixels: number;
}

