// Interface automatically generated by schemas-to-ts

export interface Quote {
  quote: string;
  attribution?: string;
}
export interface Quote_Plain {
  quote: string;
  attribution?: string;
}

export interface Quote_NoRelations {
  quote: string;
  attribution?: string;
}

