// Interface automatically generated by schemas-to-ts

export interface Subtitle {
  text: string;
}
export interface Subtitle_Plain {
  text: string;
}

export interface Subtitle_NoRelations {
  text: string;
}

