// Interface automatically generated by schemas-to-ts

export interface Text {
  text: string;
  title?: string;
  centerAlign: boolean;
}
export interface Text_Plain {
  text: string;
  title?: string;
  centerAlign: boolean;
}

export interface Text_NoRelations {
  text: string;
  title?: string;
  centerAlign: boolean;
}

