// Interface automatically generated by schemas-to-ts

export interface TitleHeader {
  title: string;
}
export interface TitleHeader_Plain {
  title: string;
}

export interface TitleHeader_NoRelations {
  title: string;
}

