// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface WideImage {
  image: { data: Media };
  addPaddingOnLeftAndRight: boolean;
}
export interface WideImage_Plain {
  image: Media_Plain;
  addPaddingOnLeftAndRight: boolean;
}

export interface WideImage_NoRelations {
  image: number;
  addPaddingOnLeftAndRight: boolean;
}

