// Interface automatically generated by schemas-to-ts

export interface Redirect {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    from: string;
    to: string;
    isPermanent: boolean;
  };
}
export interface Redirect_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  from: string;
  to: string;
  isPermanent: boolean;
}

export interface Redirect_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  from: string;
  to: string;
  isPermanent: boolean;
}

export interface Redirect_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  from: string;
  to: string;
  isPermanent: boolean;
}
