// Interface automatically generated by schemas-to-ts

export interface ContactPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    pageTitle: string;
    belowFormText?: string;
    aboveFormText?: string;
    pageDescription: string;
    locale: string;
    localizations?: { data: ContactPage[] };
  };
}
export interface ContactPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  pageTitle: string;
  belowFormText?: string;
  aboveFormText?: string;
  pageDescription: string;
  locale: string;
  localizations?: ContactPage_Plain[];
}

export interface ContactPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  pageTitle: string;
  belowFormText?: string;
  aboveFormText?: string;
  pageDescription: string;
  locale: string;
  localizations?: ContactPage[];
}

export interface ContactPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  pageTitle: string;
  belowFormText?: string;
  aboveFormText?: string;
  pageDescription: string;
  locale: string;
  localizations?: ContactPage[];
}
