// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Link } from '../../../../components/link/interfaces/Link';
import { BulletPoint } from '../../../../components/general/interfaces/BulletPoint';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Link_Plain } from '../../../../components/link/interfaces/Link';
import { BulletPoint_Plain } from '../../../../components/general/interfaces/BulletPoint';
import { Link_NoRelations } from '../../../../components/link/interfaces/Link';
import { BulletPoint_NoRelations } from '../../../../components/general/interfaces/BulletPoint';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Homepage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    heroImageText: string;
    heroImage: { data: Media };
    heroImageCallToActionImage: { data: Media };
    heroImageCallToActionText?: string;
    heroImageDarkenPercent?: number;
    missionStatementBackgroundImage: { data: Media };
    missionStatementTitle: string;
    missionStatementSubtitle: string;
    missionStatementText: string;
    missionStatementButton: Link;
    featuredVideo: { data: Media };
    featuredVideoDescription: string;
    detailedAboutSectionImage: { data: Media };
    detailedAboutSectionText: string;
    detailedAboutSectionBulletPoints: BulletPoint[];
    detailedAboutSectionButton: Link;
    collageImage1: { data: Media };
    collageButton1: Link;
    collageImage2: { data: Media };
    collageButton2: Link;
    collageImage3: { data: Media };
    collageButton3: Link;
    collageImage4: { data: Media };
    collageButton4: Link;
    carouselImages: { data: Media[] };
    locale: string;
    localizations?: { data: Homepage[] };
  };
}
export interface Homepage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  heroImageText: string;
  heroImage: Media_Plain;
  heroImageCallToActionImage: Media_Plain;
  heroImageCallToActionText?: string;
  heroImageDarkenPercent?: number;
  missionStatementBackgroundImage: Media_Plain;
  missionStatementTitle: string;
  missionStatementSubtitle: string;
  missionStatementText: string;
  missionStatementButton: Link_Plain;
  featuredVideo: Media_Plain;
  featuredVideoDescription: string;
  detailedAboutSectionImage: Media_Plain;
  detailedAboutSectionText: string;
  detailedAboutSectionBulletPoints: BulletPoint_Plain[];
  detailedAboutSectionButton: Link_Plain;
  collageImage1: Media_Plain;
  collageButton1: Link_Plain;
  collageImage2: Media_Plain;
  collageButton2: Link_Plain;
  collageImage3: Media_Plain;
  collageButton3: Link_Plain;
  collageImage4: Media_Plain;
  collageButton4: Link_Plain;
  carouselImages: Media_Plain[];
  locale: string;
  localizations?: Homepage_Plain[];
}

export interface Homepage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  heroImageText: string;
  heroImage: number;
  heroImageCallToActionImage: number;
  heroImageCallToActionText?: string;
  heroImageDarkenPercent?: number;
  missionStatementBackgroundImage: number;
  missionStatementTitle: string;
  missionStatementSubtitle: string;
  missionStatementText: string;
  missionStatementButton: Link_NoRelations;
  featuredVideo: number;
  featuredVideoDescription: string;
  detailedAboutSectionImage: number;
  detailedAboutSectionText: string;
  detailedAboutSectionBulletPoints: BulletPoint_NoRelations[];
  detailedAboutSectionButton: Link_NoRelations;
  collageImage1: number;
  collageButton1: Link_NoRelations;
  collageImage2: number;
  collageButton2: Link_NoRelations;
  collageImage3: number;
  collageButton3: Link_NoRelations;
  collageImage4: number;
  collageButton4: Link_NoRelations;
  carouselImages: number[];
  locale: string;
  localizations?: Homepage[];
}

export interface Homepage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  heroImageText: string;
  heroImage: AdminPanelRelationPropertyModification<Media_Plain>;
  heroImageCallToActionImage: AdminPanelRelationPropertyModification<Media_Plain>;
  heroImageCallToActionText?: string;
  heroImageDarkenPercent?: number;
  missionStatementBackgroundImage: AdminPanelRelationPropertyModification<Media_Plain>;
  missionStatementTitle: string;
  missionStatementSubtitle: string;
  missionStatementText: string;
  missionStatementButton: Link_Plain;
  featuredVideo: AdminPanelRelationPropertyModification<Media_Plain>;
  featuredVideoDescription: string;
  detailedAboutSectionImage: AdminPanelRelationPropertyModification<Media_Plain>;
  detailedAboutSectionText: string;
  detailedAboutSectionBulletPoints: BulletPoint_Plain[];
  detailedAboutSectionButton: Link_Plain;
  collageImage1: AdminPanelRelationPropertyModification<Media_Plain>;
  collageButton1: Link_Plain;
  collageImage2: AdminPanelRelationPropertyModification<Media_Plain>;
  collageButton2: Link_Plain;
  collageImage3: AdminPanelRelationPropertyModification<Media_Plain>;
  collageButton3: Link_Plain;
  collageImage4: AdminPanelRelationPropertyModification<Media_Plain>;
  collageButton4: Link_Plain;
  carouselImages: AdminPanelRelationPropertyModification<Media_Plain>[];
  locale: string;
  localizations?: Homepage[];
}
