// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Homepage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    heroImageText: string;
    heroImage: { data: Media };
    heroImageCallToActionImage: { data: Media };
    heroImageCallToActionText?: string;
    locale: string;
    localizations?: { data: Homepage[] };
  };
}
export interface Homepage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  heroImageText: string;
  heroImage: Media_Plain;
  heroImageCallToActionImage: Media_Plain;
  heroImageCallToActionText?: string;
  locale: string;
  localizations?: Homepage_Plain[];
}

export interface Homepage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  heroImageText: string;
  heroImage: number;
  heroImageCallToActionImage: number;
  heroImageCallToActionText?: string;
  locale: string;
  localizations?: Homepage[];
}

export interface Homepage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  heroImageText: string;
  heroImage: AdminPanelRelationPropertyModification<Media_Plain>;
  heroImageCallToActionImage: AdminPanelRelationPropertyModification<Media_Plain>;
  heroImageCallToActionText?: string;
  locale: string;
  localizations?: Homepage[];
}
